apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim  # Nom de la PVC pour identifier le stockage
spec:
  volumeMode: Filesystem    # Type de volume : système de fichiers
  accessModes:
    - ReadWriteOnce         # Le volume ne peut être monté en lecture-écriture que par un seul nœud à la fois
  resources:
    requests:
      storage: 500Mi         # Quantité de stockage demandée pour la PVC
  storageClassName: default  # Assurez-vous que le StorageClass est correctement défini, ici par défaut
slim [ ~/k8s/spring ]$ 
